hand_name: "dom"
baudrate: 4000000
device_name: "/dev/ttyUSB0"
pub_pos: true
pub_vel: false
pub_current: false
kP: 600
kI: 0
kD: 200
curr_lim: 5000
start_pos: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
